// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUO75_Y8CvJtmi2Fqh_EyGeWBOqQV2gk',
    appId: '1:236712331640:android:e086f8ca84a967849c208d',
    messagingSenderId: '236712331640',
    projectId: 'test-1b77a',
    storageBucket: 'test-1b77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkDHCPzly7nAjjOa-UpcQE4yAVOAWH8I',
    appId: '1:236712331640:ios:99f7b8c4be384f7e9c208d',
    messagingSenderId: '236712331640',
    projectId: 'test-1b77a',
    storageBucket: 'test-1b77a.firebasestorage.app',
    androidClientId: '236712331640-fumivp9p8vtlo7j9s10it2da4lf8601c.apps.googleusercontent.com',
    iosClientId: '236712331640-vuee2jhds7n9jpqhqi8of29ht5pfergd.apps.googleusercontent.com',
    iosBundleId: 'com.example.breadcrumbs',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyfMMBeyzm8SKbjot6qhkZ1R26hQumgn8',
    appId: '1:236712331640:web:7433616337e3767a9c208d',
    messagingSenderId: '236712331640',
    projectId: 'test-1b77a',
    authDomain: 'test-1b77a.firebaseapp.com',
    storageBucket: 'test-1b77a.firebasestorage.app',
    measurementId: 'G-RH717J7S45',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIkDHCPzly7nAjjOa-UpcQE4yAVOAWH8I',
    appId: '1:236712331640:ios:99f7b8c4be384f7e9c208d',
    messagingSenderId: '236712331640',
    projectId: 'test-1b77a',
    storageBucket: 'test-1b77a.firebasestorage.app',
    androidClientId: '236712331640-fumivp9p8vtlo7j9s10it2da4lf8601c.apps.googleusercontent.com',
    iosClientId: '236712331640-vuee2jhds7n9jpqhqi8of29ht5pfergd.apps.googleusercontent.com',
    iosBundleId: 'com.example.breadcrumbs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyfMMBeyzm8SKbjot6qhkZ1R26hQumgn8',
    appId: '1:236712331640:web:10b602cce8e871049c208d',
    messagingSenderId: '236712331640',
    projectId: 'test-1b77a',
    authDomain: 'test-1b77a.firebaseapp.com',
    storageBucket: 'test-1b77a.firebasestorage.app',
    measurementId: 'G-7RJSLXTTK8',
  );

}